server:
  port: 8771

spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    #prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://peer1:8760/eureka/